package tn.esprit.tttf.controller;

import java.net.URL;
import java.util.ResourceBundle;

import tn.esprit.tttf.utils.ControlledScreen;
import tn.esprit.tttf.utils.ScreensController;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.paint.Color;
import javafx.event.ActionEvent;
import javafx.scene.image.ImageView;
import javafx.scene.text.Font;
import javafx.scene.control.Hyperlink;

public class AccueilController implements Initializable,ControlledScreen {
	@FXML
	private Color x1;
	@FXML
	private Font x2;
	@FXML
	private Button bon;
	@FXML
	private Hyperlink connecter;
	@FXML
	private Font x4;
	@FXML
	private Color x3;
	
	public ScreensController screencontroller;

	// Event Listener on Button.onAction
	@FXML
	public void accueilBoxOffice(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void accueilNews(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void accueilEvents(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bon].onAction
	@FXML
	public void accueilBonsPlans(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Hyperlink[#connecter].onAction
	@FXML
	public void authentifier(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Hyperlink.onAction
	@FXML
	public void inscrire(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void SetScreenParent(ScreensController screenpage) {
		screencontroller = screenpage;
		
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
